version: "3"
services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  restart: on-failure
  ports:
   - 443:443
  volumes:
   - /home/hharit/data/wordpress:/var/www/html
  networks:
   - network
  depends_on:
   - wordpress
 mariadb:
  container_name: mariadb
  build : ./requirements/mariadb
  restart: on-failure
  ports:
    - 3306:3306
  environment:
    - .env 
 wordpress:      
  container_name: wordpress
  build: ./requirements/wordpress
  restart: on-failure
  volumes:
      - /home/hharit/data/wordpress:/var/www/html
  networks:
   - network
  ports:
   - 9000:9000

volumes:
 wordpress:
  driver: local
  driver_opts:
    type: none
    device: /Users/hharit/data/wordpress
    o: bind
networks:
 network :
  driver: bridge
