version: "3"
services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  restart: on-failure
  ports:
   - 443:443
  volumes:
   - ./data:/var/www/html/wordpress
  networks:
   - network
 mariadb:
  container_name: mariadb
  build : ./requirements/mariadb
  restart: on-failure
  ports:
    - 3306:3306
  environment:
    - .env 
 wordpress:      
  container_name: wordpress
  build: ./requirements/wordpress
  restart: on-failure
  volumes:
    - ./data:/var/www/html/wordpress
  networks:
    - network
volumes:
 data:
  driver: local
  driver_opts:
   type: none
   device: /home/hharit/data/wordpress
networks:
 network :
  driver: bridge
