version: "3"
services:
 nginx:
  container_name: nginx_container
  build: ./requirements/nginx
  image: nginx
  restart: on-failure
  ports:
   - 443:443
  volumes:
   - wordpress:/var/www/html/wordpress
  networks:
   - network
  depends_on:
   - wordpress
  env_file:
   - .env
  
 mariadb:
  container_name: mariadb_container
  build : ./requirements/mariadb
  image: mariadb
  restart: on-failure
  ports:
    - 3306:3306
  networks:
    - network
  env_file:
    - .env
  volumes:
    - mariadb:/var/lib/mysql

 wordpress:      
  depends_on:
   - mariadb
  container_name: wordpress_container
  build: ./requirements/wordpress
  image: wordpress
  restart: on-failure
  volumes:
   - wordpress:/var/www/html/wordpress
  networks:
   - network
  ports:
   - 9000:9000
  env_file:
   - .env

volumes:
 wordpress:
  driver: local
  driver_opts:
    type: none
    device: /home/hharit/data/wordpress
    o: bind
 mariadb:
  driver: local
  driver_opts:
    type: none
    device: /home/hharit/data/mariadb
    o: bind


networks:
 network :
  driver: bridge
