version: "3"
services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  restart: on-failure
  ports:
   - 443:443
 mariadb:
   container_name: mariadb
   build : ./requirements/mariadb
   restart: on-failure
   ports:
     - 3306:3306
   environment:
     - .env 
 php-fpm:      
   container_name: php-fpm
   build: ./requirements/wordpress
   ports:
       - 9000:9000
   #restart: on-failure
