version: "3"
services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  restart: on-failure
  ports:
   - 443:443
  volumes:
   - wordpress:/var/www/html/wordpress
  networks:
   - network
  depends_on:
   - wordpress

 mariadb:
  container_name: mariadb
  build : ./requirements/mariadb
  restart: on-failure
  ports:
    - 3306:3306
  networks:
    - network
  environment:
    - .env
 wordpress:      
  container_name: wordpress
  build: ./requirements/wordpress
  restart: on-failure
  volumes:
      - wordpress:/var/www/html/wordpress
  networks:
   - network
  ports:
   - 9000:9000
  environment:
   - .env

volumes:
 wordpress:
  driver: local
  driver_opts:
    type: none
    device: /home/hharit/data/wordpress
    o: bind

networks:
 network :
  driver: bridge
