services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  restart: on-failure
  ports:
   - 443:443
 mariadb:
  container_name: mariadb
  build : ./requirements/mariadb
  restart: on-failure
  env_file:
    - .env
