version: "3"
services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx
  restart: on-failure
  ports:
   - 443:443
 mariadb:
   container_name: mariadb
   build : ./requirements/mariadb
   restart: on-failure
   ports:
     - 3306:3306
   environment:
     - .env 
